### ISSUE TITLE
Tensorflow / GPU devide / ROI Pooling layer

### ISSUE THREAD

**Issue by vhtrivedi** [smallcorgi/Faster-RCNN_TF#111]
Sorry for the vague title, but I was not able to run the demo on CPU. Got the following message. 

vedant@vedant-550P5C-550P7C:~/FRCN_ROOT$ python ./tools/demo.py --model /home/vedant/FRCN_ROOT/VGGnet_fast_rcnn_iter_70000.ckpt
Traceback (most recent call last):
  File "./tools/demo.py", line 11, in <module>
    from networks.factory import get_network
  File "/home/vedant/FRCN_ROOT/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/vedant/FRCN_ROOT/tools/../lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "/home/vedant/FRCN_ROOT/tools/../lib/networks/network.py", line 3, in <module>
    import roi_pooling_layer.roi_pooling_op as roi_pool_op
  File "/home/vedant/FRCN_ROOT/tools/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/vedant/FRCN_ROOT/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _Z22ROIPoolBackwardLaucherPKffiiiiiiiS0_PfPKiRKN5Eigen9GpuDeviceE

I did come across people have the same problem earlier on another issue thread. Wanting to know if someone has found a solution to this till now.

**Comment by guotong1988** [comment]
I succeed to run another faster-rcnn on CPU from [this repo](https://github.com/endernewton/tf-faster-rcnn)

**Comment by villasu0313** [comment]
@guotong1988 how did you run in this
