### ISSUE TITLE
error running the demo

### ISSUE THREAD

**Issue by kirk86** [smallcorgi/Faster-RCNN_TF#112]
hi thanks for this. I've tried following the guide in order to run the demo but I've run into the following errors. Any suggestions?

```
# python demo.py ../VGGnet_fast_rcnn_iter_70000.ckpt --gpu 0
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from networks.factory import get_network
  File "/output/frcnn/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/output/frcnn/tools/../lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "/output/frcnn/tools/../lib/networks/network.py", line 3, in <module>
    import roi_pooling_layer.roi_pooling_op as roi_pool_op
  File "/output/frcnn/tools/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /output/frcnn/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbo
l: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumE
```

**Comment by SaverioSun** [comment]
I meet the same error

**Comment by towardthesea** [comment]
Please have look at this [issue](https://github.com/smallcorgi/Faster-RCNN_TF/issues/25)

**Comment by zjz5250** [comment]
l have added "-D_GLIBCXX_USE_CXX11_ABI=0 ",but a new error occurred,as follows:
Traceback (most recent call last):
  File "demo.py", line 11, in <module>
    from networks.factory import get_network
  File "/home/tf/Downloads/Faster-RCNN_TF/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/tf/Downloads/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "/home/tf/Downloads/Faster-RCNN_TF/tools/../lib/networks/network.py", line 3, in <module>
    import roi_pooling_layer.roi_pooling_op as roi_pool_op
  File "/home/tf/Downloads/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/tf/Downloads/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _Z22ROIPoolBackwardLaucherPKffiiiiiiiS0_PfPKiRKN5Eigen9GpuDeviceE

**Comment by crazymxm** [comment]
@zjz5250 I have the same error with u.   I am using cpu

**Comment by crazymxm** [comment]
I had fix this problem ：[here](https://github.com/crazymxm/Faster-RCNN_TF/commit/0dcb55cebeaa85c9f0a46ff62384bbeaae98323e)

**Comment by jcggg** [comment]
@crazymxm I have tried your solution, and it works for me. My platform is raspberry pi. GCC/G++ version 6.3.0.
Thanks a lot!!!

**Comment by lijf138** [comment]
I have the same error with you @kirk86 

tensorflow.python.framework.errors_impl.NotFoundError: /home/ii/app/Faster-RCNN_TF-master/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

I am using gpu :
cuda9.0 cudnn7.1 python3.5 tensorflow1.10 ubuntu18.04
