### ISSUE TITLE
Cannot make ! It is a problem of Cython?

### ISSUE THREAD

**Issue by shuuchen** [smallcorgi/Faster-RCNN_TF#115]
Hi there,

I tried to run the following command:

cd $FRCN_ROOT/lib
make

but it cannot run.

It is an issue of Cython? or something others?

**Comment by AlbertoBenini** [comment]
So when you run make nothing happend? Or do you have an error?

**Comment by shuuchen** [comment]
I just wonder what should be installed first to run 'make' command. Is that Cython?

**Comment by AlbertoBenini** [comment]
Yes, you have to install Cython in order to make the project

**Comment by shuuchen** [comment]
I installed that with the following version:

>Cython -V
Cython version 0.23.4

But nothing happens when I typed the 'make' command.

**Comment by LHagendoorn** [comment]
What operating system are you running? And, as Alberto said, what error are you getting? There is no way *nothing* happens right?

**Comment by shuuchen** [comment]
Windows 10 Home

**Comment by LHagendoorn** [comment]
Well there's your problem. (Just tell us your error next time, makes things a loooot easier) http://stackoverflow.com/questions/2532234/how-to-run-a-makefile-in-windows here they explain something about running Makefiles under windows. My suggestion is to just use something like Docker to run this network under Linux, making these kind of things work on windows is not fun. (Although windows 10 has a bash terminal you can try, but that is still in development and last time I checked it couldn't access your gpu)

**Comment by shuuchen** [comment]
Thanks very much for the solution!
I will try that!

**Comment by shuuchen** [comment]
I tried that but got the following errors:

$ make
python setup.py build_ext --inplace
running build_ext
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "C:\Users\to\Anaconda3\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Users\to\Anaconda3\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "C:\Users\to\Anaconda3\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\to\Anaconda3\lib\site-packages\Cython\Distutils\build_ext.py", line 164, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\to\Anaconda3\lib\distutils\command\build_ext.py", line 338, in run
    self.build_extensions()
  File "setup.py", line 105, in build_extensions
    customize_compiler_for_nvcc(self.compiler)
  File "setup.py", line 77, in customize_compiler_for_nvcc
    default_compiler_so = self.compiler_so
AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
make: *** [Makefile:2: all] error 1

$ python -V
Python 3.5.1 :: Anaconda 4.0.0 (64-bit)

Is that a python version error? or something else?

**Comment by shuuchen** [comment]
I do not have a GPU on my computer so it cannot run CUDA code.
Is that a problem?

**Comment by AlbertoBenini** [comment]
For the cpu you should be able to run the code, clearly it will be slower than on gpu. 
For the error I think that it's a problem of MSVCCompiler. Try to google it

**Comment by LHagendoorn** [comment]
Trying to make this stuff under windows is just a really bad idea. Especially without an Nvidia gpu (you will definetly be unable to train this, but if you only want to run it, a CPU will work).
For starters you will need python 2.7, other than that, I can't help you with compiling this under windows, other than again recommending using virtual box or docker to run this under linux.

**Comment by shuuchen** [comment]
OK.
Thanks very much for the answers.

**Comment by HaoWangDL** [comment]
@shuuchen have you resolved the question,I have the same question,thanks?

**Comment by shuuchen** [comment]
@HaoWangDL 
I gave up Windows and move to Linux. The problem didn't happen any more.

**Comment by HaoWangDL** [comment]
@shuuchen  thank you ! I'm doing the same.

**Comment by HaoWangDL** [comment]
@shuuchen  hi,have you meet the question  no module named fast_rcnn on linux?it confused me 2 days.thanks

**Comment by ankur7721** [comment]
@HaoWangDL that's the problem of relative path.
