### ISSUE TITLE
running demo.py error

### ISSUE THREAD

**Issue by 714586886** [smallcorgi/Faster-RCNN_TF#122]
Env:
Tensorflow 1.0.1  
Ubuntu 16.04
CUDA 8.0
Cudnn 5.1

When i run the code:
 python ./tools/demo.py --model ./VGGnet_fast_rcnn_iter_70000.ckpt

I get error:

failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED

Traceback (most recent call last):
  File "./tools/demo.py", line 126, in <module>
    _, _= im_detect(sess, net, im)
  File "/home/tangshouquan/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 179, in im_detect
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Blas SGEMM launch failed : m=1369, n=18, k=512
	 [[Node: rpn_cls_score/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="VALID", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](rpn_conv/3x3/rpn_conv/3x3, rpn_cls_score/weights/read)]]
	 [[Node: cls_score/cls_score/_109 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_357_cls_score/cls_score", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

how to fix it?

**Comment by 714586886** [comment]
out of memory!

**Comment by aishik-pyne** [comment]
I had the same problem, the program crashed before flushing the memory and it remained occupied.
You can try placing  `cudaDeviceReset()` before your code.
A simple restart also helped clear up the memory.

**Comment by David-Lee-1990** [comment]
Hi, have you fixed your problem?  I am training my own data using tensorflow object detection api, and i meet a similar error as yours. @714586886
