### ISSUE TITLE
The error occured when I run the demo.py

### ISSUE THREAD

**Issue by DeepStillWater** [smallcorgi/Faster-RCNN_TF#147]
The error occured when I run the demo.py

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    from networks.factory import get_network
  File "/root/netdisk/gitlab/Faster-RCNN_TF/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/root/netdisk/gitlab/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 2,in <module>
    from network import Network
  File "../lib/networks/network.py", line 6, in <module>
    import roi_pooling_layer.roi_pooling_op_grad
  File "/root/netdisk/gitlab/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling_op_grad.py", line 5, in <module>
    import roi_pooling_op
  File "../lib/roi_pooling_layer/roi_pooling_op.py", line 6, in <module>
    roi_pool = roi_pooling_module.roi_pool
AttributeError: module 'e728c87382bd3be30157f0e87e93b6e0' has no attribute 'roi_pool'

what's the problem,how can I fix it?

**Comment by amirhfarzaneh** [comment]
This is solved here [Issue #50](https://github.com/smallcorgi/Faster-RCNN_TF/issues/50)

**Comment by DeepStillWater** [comment]
I follow the steps ,but the same error.@amirhfarzaneh

**Comment by 19931991** [comment]
Do you have solved the problem ? @DeepStillWater  I try the method https://github.com/smallcorgi/Faster-RCNN_TF/issues/50 , but it did not work. @amirhfarzaneh
