### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by hadign20** [smallcorgi/Faster-RCNN_TF#155]
I'm trying to perform faster rcnn on a new dataset. I have replaced the images, annotations and ImageSets in **Pacsl VOC** with my own dataset based on the same format. It does work fine with the original Pacsl VOC, but with the new dataset I get this error:

```
Loaded dataset `voc_2007_trainval` for training
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "./tools/train_net.py", line 83, in <module>
    roidb = get_training_roidb(imdb)
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/fast_rcnn/train.py", line 204, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/datasets/imdb.py", line 108, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/datasets/imdb.py", line 69, in roidb
    self._roidb = self.roidb_handler()
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/datasets/pascal_voc.py", line 107, in gt_roidb
    for index in self.image_index]
  File "/home/hadi/Software/tensorflow/TEST_FRCN_ROOT/tools/../lib/datasets/pascal_voc.py", line 212, in _load_pascal_annotation
    cls = self._class_to_ind[obj.find('name').text.lower().strip()]
AttributeError: 'NoneType' object has no attribute 'lower'
```
I don't know if it means that the Annotation files (.xml) are missing some attribute somewhere. How can I make it work?

**Comment by GalymzhanAbdimanap** [comment]
did you find a mistake? I also have such a problem. Sorry for my english
