### ISSUE TITLE
error:run demo.py on my own model

### ISSUE THREAD

**Issue by shiwenhao** [smallcorgi/Faster-RCNN_TF#166]
Demo for data/demo/000542.jpg
Traceback (most recent call last):
  File "demo.py", line 130, in <module>
    demo(sess, net, im_name)
  File "demo.py", line 60, in demo
    scores, boxes = im_detect(sess, net, im)
  File "/home/qz/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 145, in im_detect
    blobs, im_scales = _get_blobs(im, boxes)
  File "/home/qz/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 97, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im)
  File "/home/qz/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 29, in _get_image_blob
    im_orig = im.astype(np.float32, copy=True)
AttributeError: 'NoneType' object has no attribute 'astype'
Could anyone meet this problem?Thank you for your help

**Comment by deanSunny** [comment]
check image path

**Comment by limwenyao** [comment]
Refer to my answer here: #187
