### ISSUE TITLE
pickle.dump: TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by gdelab** [smallcorgi/Faster-RCNN_TF#170]
Hi ! I'm using this repository on my own data, following #3 . I'm using python 3 (using 2to3 and several minor changes, as explained in #75 ), but while testing I get this error, do you guys know why ? 

(I actually got the same one on the pickel functions in voc_eval(), but I basically removed the cache file to avoid the error)

```
Traceback (most recent call last):
  File "./tools/test_net.py", line 97, in <module>
    test_net(sess, network, imdb, weights_filename)
  File "/home/gdelaboulaye/faster-rcnn/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 345, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/gdelaboulaye/faster-rcnn/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 329, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/gdelaboulaye/faster-rcnn/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 296, in _do_python_eval
    pickle.dump({'rec': rec, 'prec': prec, 'ap': ap}, f)
TypeError: must be str, not bytes
```

**Comment by gdelab** [comment]
I've actually solved it. It was due to moving to python 3:

You actually need to open files in byte mode before using pickle in python 3.x: 

        with open(cachefile, 'wb') as f:  #  'w' replaced by 'wb' to avoid crashing
            pickle.dump(recs, f)
        ...
        with open(cachefile, 'rb') as f:
            recs = pickle.load(f)
        ...
            with open(cache_file, 'rb') as fid:
                roidb = pickle.load(fid)
