### ISSUE TITLE
Error when flipping images

### ISSUE THREAD

**Issue by gdelab** [smallcorgi/Faster-RCNN_TF#173]
I'm training on my own data (in python 3), which seems to work when I don't flip images. However, when I use `__C.TRAIN.USE_FLIPPED = True`, I get the following error:

```
Traceback (most recent call last):
  File "./tools/train_net.py", line 83, in <module>
    roidb = get_training_roidb(imdb)
  File "/home/gdelaboulaye/faster-rcnn/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 204, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/gdelaboulaye/faster-rcnn/Faster-RCNN_TF/tools/../lib/datasets/imdb.py", line 113, in append_flipped_images
    assert (boxes[:, 2] >= boxes[:, 0]).all()
AssertionError

```

Do you guys have any idea how this can happen ?

**Comment by gdelab** [comment]
The problem was actually with my data, I had bounding boxes going out of the frame

**Comment by MitraTj** [comment]
I have this problem when I reduce the number of image database for training.
any one help?
