### ISSUE TITLE
tkinter.TclError

### ISSUE THREAD

**Issue by yang1997yi** [smallcorgi/Faster-RCNN_TF#195]
Detection took 0.639s for 300 object proposals
Traceback (most recent call last):
  File "tools/demo.py", line 136, in <module>
    demo(sess, net, im_name)
  File "tools/demo.py", line 73, in demo
    fig, ax = plt.subplots(figsize=(12, 12))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 1202, in subplots
    fig = figure(**fig_kw)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

what should I do

**Comment by Lostwayzxc** [comment]
i have the same problem, have you solved it?

**Comment by wingNine** [comment]
are your problem have solved ?

**Comment by ShiqiLi047** [comment]
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import numpy as np

above this two lines must be in the top codes
