### ISSUE TITLE
AP = -1 for every class on custom dataset

### ISSUE THREAD

**Issue by thanasissdr** [smallcorgi/Faster-RCNN_TF#196]
After a big number of iterations (~100K), I get AP = -1 for every class. Do you have any idea what could possibly go wrong? During the training there is nothing strange oserved, e.g. `loss_= nan`

**Comment by gdelab** [comment]
What are your class names ? It might come from upper case letters somewhere, since they are put to lower case in some parts of the code but not all (if I remember correctly).

**Comment by Suodislie** [comment]
Hello， I want know how did you get the AP ?  when i run the test.py iget an error：
...
im_detect: 4951/4952 0.505s 0.001s
im_detect: 4952/4952 0.505s 0.001s
Evaluating detections
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
File "./tools/test_net.py", line 98, in 
test_net(sess, network, imdb, weights_filename)
File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 345, in test_net
imdb.evaluate_detections(all_boxes, output_dir)
File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 325, in evaluate_detections
self._do_python_eval(output_dir)
File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 288, in _do_python_eval
use_07_metric=use_07_metric)
File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/datasets/voc_eval.py", line 126, in voc_eval
R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '000001'
Hope for your help ,Ths!

**Comment by thanasissdr** [comment]
@gdelab My class labels have only lowercase letters and numbers.

**Comment by thanasissdr** [comment]
@Suodislie Sorry, I can't help you I haven't trained the network with the original dataset. But, this might help you. https://github.com/rbgirshick/py-faster-rcnn/issues/163

**Comment by Zealoe** [comment]
@thanasissdr How do you fix the problem?

**Comment by thanasissdr** [comment]
@Zealoe If my level of understanding is correct, this occurs when there are no objects found belonging to a specific class. First of all, try to see if all the coordinates of the bounding boxes referring to the ground truth do not contain any negative values.

**Comment by Zealoe** [comment]
@thanasissdr  Thanks for your reply. But I have checked the dataset. I think the data has no problem....and if i test with the pretrained model, it works well.     So it should be the problem with the training process. And did you change any params? because i use the original params in this repository...

**Comment by hxf930620** [comment]
@thanasissdr have you solved this probiem?

**Comment by lipikak17** [comment]
@thanasissdr have you solved the problem?
