### ISSUE TITLE
KeyError: '000001' problem

### ISSUE THREAD

**Issue by ghost** [smallcorgi/Faster-RCNN_TF#199]
i training a model ,i meet a problem what is called KeyError: '000001',the detail as followed ,what should i do.thanks!
...
im_detect: 4951/4952 0.505s 0.001s
im_detect: 4952/4952 0.505s 0.001s
Evaluating detections
Writing aeroplane VOC results file
Writing bicycle VOC results file
Writing bird VOC results file
Writing boat VOC results file
Writing bottle VOC results file
Writing bus VOC results file
Writing car VOC results file
Writing cat VOC results file
Writing chair VOC results file
Writing cow VOC results file
Writing diningtable VOC results file
Writing dog VOC results file
Writing horse VOC results file
Writing motorbike VOC results file
Writing person VOC results file
Writing pottedplant VOC results file
Writing sheep VOC results file
Writing sofa VOC results file
Writing train VOC results file
Writing tvmonitor VOC results file
VOC07 metric? Yes
Traceback (most recent call last):
  File "./tools/test_net.py", line 98, in <module>
    test_net(sess, network, imdb, weights_filename)
  File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 345, in test_net
    imdb.evaluate_detections(all_boxes, output_dir)
  File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 325, in evaluate_detections
    self._do_python_eval(output_dir)
  File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/datasets/pascal_voc.py", line 288, in _do_python_eval
    use_07_metric=use_07_metric)
  File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/datasets/voc_eval.py", line 126, in voc_eval
    R = [obj for obj in recs[imagename] if obj['name'] == classname]
KeyError: '000001'

**Comment by Suodislie** [comment]
Hello， I met the same question，did you have solved it ？

**Comment by Akansha06** [comment]
grep "000001" inside annotation folder. Somewhere in any of xml file. You have defined class as "000001".

**Comment by Akansha06** [comment]
@Suodislie Clear your cache files before starting any training.

**Comment by liuxinhai** [comment]
this might help you.https://github.com/rbgirshick/py-faster-rcnn/issues/163

**Comment by JFishLover** [comment]
thanks @liuxinhai
