### ISSUE TITLE
InvalidArgumentError (see above for traceback): TypeError: 'float' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Kienlgk** [smallcorgi/Faster-RCNN_TF#231]
Hi.
When I try 6th step in Training Model:
```
$ ./experiments/scripts/faster_rcnn_end2end.sh gpu 0 VGG16 pascal_voc
```
I met the following error:
```
...
assign pretrain model biases to conv2_2
assign pretrain model weights to conv2_1
assign pretrain model biases to conv2_1
2017-11-02 10:49:00.086797: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: TypeError: 'float' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: 'float' object cannot be interpreted as an integer
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_105, _arg_Placeholder_2_0_2, roi-data/PyFunc/input_2)]]
	 [[Node: roi-data/PyFunc/_107 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_301_roi-data/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/fast_rcnn/train.py", line 266, in train_net
    sw.train_model(sess, max_iters)
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/fast_rcnn/train.py", line 180, in train_model
    run_metadata=run_metadata)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: TypeError: 'float' object cannot be interpreted as an integer
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_105, _arg_Placeholder_2_0_2, roi-data/PyFunc/input_2)]]
	 [[Node: roi-data/PyFunc/_107 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_301_roi-data/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op 'roi-data/PyFunc', defined at:
  File "./tools/train_net.py", line 91, in <module>
    network = get_network(args.network_name)
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/networks/factory.py", line 30, in get_network
    return networks.VGGnet_train()
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/networks/VGGnet_train.py", line 20, in __init__
    self.setup()
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/networks/VGGnet_train.py", line 77, in setup
    .proposal_target_layer(n_classes,name = 'roi-data'))
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/bk/Kien/faster-rcnn-smallcorgi/tools/../lib/networks/network.py", line 189, in proposal_target_layer
    rois,labels,bbox_targets,bbox_inside_weights,bbox_outside_weights = tf.py_func(proposal_target_layer_py,[input[0],input[1],classes],[tf.float32,tf.float32,tf.float32,tf.float32,tf.float32])
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 198, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 38, in _py_func
    name=name)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/bk/anaconda3/envs/tfgpu/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): TypeError: 'float' object cannot be interpreted as an integer
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_105, _arg_Placeholder_2_0_2, roi-data/PyFunc/input_2)]]
	 [[Node: roi-data/PyFunc/_107 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_301_roi-data/PyFunc", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```
The issue seems like #72 
How can I solve this?
Thank in advanced.

**Comment by corelli359** [comment]
oh! i have the same problem and now i still can not solve this !do you have some progress?

**Comment by Kienlgk** [comment]
My solution is changing numpy version to 1.11 with:
```
pip3 install numpy==1.11
```

**Comment by longzeyilang** [comment]
@Kienlgk https://github.com/smallcorgi/Faster-RCNN_TF/issues/287
has the same problem, Can you help me?

**Comment by YCIrving** [comment]
Instead of changing the version to 1.11, I modified the code in _lib/rpn_msr/proposal_target_layer_tf.py_, line 138-139:

`    if bg_inds.size > 0:
        bg_inds = npr.choice(bg_inds, size=bg_rois_per_this_image, replace=False)`
to
`if bg_inds.size > 0:
        bg_inds = npr.choice(bg_inds, size=int(bg_rois_per_this_image), replace=False)`

numpy.random.choice requires the second parameter to be a int type, you have to transform it manually in numpy>1.11
  
That works for me, try to find and modify the similar function calls in _proposal_target_layer_tf.py_ if you still encounter the similar problems :)
