### ISSUE TITLE
doesn't  generate image with bounding box 

### ISSUE THREAD

**Issue by jt387** [smallcorgi/Faster-RCNN_TF#237]
Hi everyone!  I trained the Faster-RCNN with no error information,  generated the train model VGGnet_fast_rcnn_iter_70000.ckpt  in the directory output/faster_rcnn_end2end/voc_2007_trainval and test results aeroplane_pr.pkl, bicycle_pr.pkl,  etc. in the directory output/faster_rcnn_end2end/voc_2007_test/VGGnet_fast_rcnn_iter_70000. 
And when I run: python tools/demo.py --model   ./output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt,  the output like:
Loaded network ./output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/000456.jpg
Detection took 0.888s for 300 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/000542.jpg
Detection took 0.194s for 219 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/001150.jpg
Detection took 0.184s for 187 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/001763.jpg
Detection took 0.187s for 204 object proposals
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/004545.jpg
Detection took 0.196s for 300 object proposals

It looks fine,  but there is no image with bounding box.  And I add "plt.savefig("faster_result.jpg")"
 after the line "plt.draw()" in the demo.py,   then goes wrong,  error as below:
Loaded network ./output/faster_rcnn_end2end/voc_2007_trainval/VGGnet_fast_rcnn_iter_70000.ckpt
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Demo for data/demo/000456.jpg
Detection took 0.894s for 300 object proposals
Traceback (most recent call last):
  File "tools/demo.py", line 137, in <module>
    demo(sess, net, im_name)
  File "tools/demo.py", line 87, in demo
    vis_detections(im, cls, dets, ax, thresh=CONF_THRESH)
  File "tools/demo.py", line 54, in vis_detections
    plt.savefig("faster_result.jpg")
  File "/home/facenano/anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/matplotlib/figure.py", line 1814, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2259, in print_figure
    **kwargs)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 584, in print_jpg
    return background.save(filename_or_obj, format='jpeg', **options)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 1682, in save
    save_handler(self, fp, filename)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 696, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/PIL/ImageFile.py", line 488, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/home/facenano/anaconda/lib/python2.7/site-packages/PIL/Image.py", line 432, in _getencoder
    return encoder(mode, *args + extra)
TypeError: integer argument expected, got float

My environment is ubuntu 14.04 + cuda8.0 + GeForce GTX TITAN BLACK
Any reply will be appreciated! Thanks!

**Comment by jt387** [comment]
changing the plt.savefig()'s  parameter ".....jpg" to "....png"  can generate the BBox images,  but also generates one empty image with the name of ....jpg,  I can't explain it.

**Comment by catubc** [comment]
Yes, .png fixed my problem also.... seems new matplotlib libraries broke my existing .jpg output code.
