### ISSUE TITLE
W tensorflow/core/framework/op_kernel.cc:1192] Unknown: NameError: name 'xrange' is not defined

### ISSUE THREAD

**Issue by ziyeshanwai** [smallcorgi/Faster-RCNN_TF#247]
I changed the code to the python3 syntax format，like replace "print " with "print()", "xrange" with "range" ect. I' m sure that I have replace all "xrange" with "range", I am using python 3.5 and tf 1.4 .however i get follow error:
2017-12-12 18:24:16.917295: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.16GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-12-12 18:24:17.130165: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 3.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-12-12 18:24:17.504940: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.79GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-12-12 18:24:17.733228: W tensorflow/core/common_runtime/bfc_allocator.cc:217] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.39GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
2017-12-12 18:24:18.779902: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: NameError: name 'xrange' is not defined
2017-12-12 18:24:18.839335: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: NameError: name 'xrange' is not defined
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/rpn_cls_score/_69, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, _arg_Placeholder_0_0, PyFunc/input_4, PyFunc/input_5)]]
2017-12-12 18:24:18.850058: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: NameError: name 'xrange' is not defined
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/rpn_cls_score/_69, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, _arg_Placeholder_0_0, PyFunc/input_4, PyFunc/input_5)]]
2017-12-12 18:24:18.850101: W tensorflow/core/framework/op_kernel.cc:1192] Unknown: NameError: name 'xrange' is not defined
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/rpn_cls_score/_69, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, _arg_Placeholder_0_0, PyFunc/input_4, PyFunc/input_5)]]
Traceback (most recent call last):
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: NameError: name 'xrange' is not defined
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/rpn_cls_score/_69, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, _arg_Placeholder_0_0, PyFunc/input_4, PyFunc/input_5)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 263, in train_net
    sw.train_model(sess, max_iters)
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 177, in train_model
    run_metadata=run_metadata)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: NameError: name 'xrange' is not defined
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/rpn_cls_score/_69, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, _arg_Placeholder_0_0, PyFunc/input_4, PyFunc/input_5)]]

Caused by op 'rpn-data/PyFunc', defined at:
  File "./tools/train_net.py", line 91, in <module>
    network = get_network(args.network_name)
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/networks/factory.py", line 30, in get_network
    return networks.VGGnet_train()
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 20, in __init__
    self.setup()
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 58, in setup
    .anchor_target_layer(_feat_stride, anchor_scales, name = 'rpn-data' ))
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/liyouwang/PycharmProjects/Faster-RCNN_TF/tools/../lib/networks/network.py", line 172, in anchor_target_layer
    rpn_labels,rpn_bbox_targets,rpn_bbox_inside_weights,rpn_bbox_outside_weights = tf.py_func(anchor_target_layer_py,[input[0],input[1],input[2],input[3], _feat_stride, anchor_scales],[tf.float32,tf.float32,tf.float32,tf.float32])
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/script_ops.py", line 212, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/gen_script_ops.py", line 50, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/liyouwang/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): NameError: name 'xrange' is not defined
	 [[Node: rpn-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_cls_score/rpn_cls_score/_69, _arg_Placeholder_2_0_2, _arg_Placeholder_1_0_1, _arg_Placeholder_0_0, PyFunc/input_4, PyFunc/input_5)]]

**Comment by artificial-mind** [comment]
hi @ziyeshanwai ,

I think you are using Python3.x version. xrange has been removed from python3.
Instead range has to be used.

Check it once.

**Comment by ziyeshanwai** [comment]
@artificial-mind you are right, i find a xrang in roidb.py , thank you

**Comment by Lostwayzxc** [comment]
have you solved this problem? I think i already replace all "xrange" with "range"
