### ISSUE TITLE
 Failed launching MaxPoolForwardNoMask

### ISSUE THREAD

**Issue by ambr89** [smallcorgi/Faster-RCNN_TF#249]
I've got this error:

Traceback (most recent call last):
  File "../tools/demo.py", line 131, in <module>
    _, _= im_detect(sess, net, im)
  File "/home/administrator/Faster-RCNN_TF/tools/../lib/fast_rcnn/test.py", line 183, in im_detect
    run_metadata=run_metadata)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed launching MaxPoolForwardNoMask
         [[Node: pool1 = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_2/conv1_2)]]
         [[Node: bbox_pred/bbox_pred/_105 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_353_bbox_pred/bbox_pred", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'pool1', defined at:
  File "../tools/demo.py", line 119, in <module>
    net = get_network(args.demo_net)
  File "/home/administrator/Faster-RCNN_TF/tools/../lib/networks/factory.py", line 28, in get_network
    return networks.VGGnet_test()
  File "/home/administrator/Faster-RCNN_TF/tools/../lib/networks/VGGnet_test.py", line 16, in __init__
    self.setup()
  File "/home/administrator/Faster-RCNN_TF/tools/../lib/networks/VGGnet_test.py", line 22, in setup
    .max_pool(2, 2, 2, 2, padding='VALID', name='pool1')
  File "/home/administrator/Faster-RCNN_TF/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/administrator/Faster-RCNN_TF/tools/../lib/networks/network.py", line 131, in max_pool
    name=name)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1772, in max_pool
    name=name)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 1605, in _max_pool
    data_format=data_format, name=name)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/administrator/venv1.3/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Failed launching MaxPoolForwardNoMask
         [[Node: pool1 = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 2, 2, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/gpu:0"](conv1_2/conv1_2)]]
         [[Node: bbox_pred/bbox_pred/_105 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_353_bbox_pred/bbox_pred", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

I've got a:
GTX 1080 Ti
tensorflow 1.3
cuda 8

**Comment by chl916185** [comment]
I've got this error:，How to solve it？
@ambr89

**Comment by ambr89** [comment]
I don't know, I've not resove it

**Comment by chl916185** [comment]
VGGnet_fast_rcnn_iter_70000.ckpt ，Where can I download it？
@ambr89

**Comment by ambr89** [comment]
I download it from [Google_drive link ](https://drive.google.com/file/d/0ByuDEGFYmWsbZ0EzeUlHcGFIVWM/view)
And I save it in externa project folder

**Comment by halegreen** [comment]
I've got same error, how to solve?
