### ISSUE TITLE
undefined symbol: PyFPE_jbuf when run demo.py

### ISSUE THREAD

**Issue by ghost** [smallcorgi/Faster-RCNN_TF#258]
python ./tools/demo.py --model model_path
Traceback (most recent call last):
  File "./tools/demo.py", line 3, in <module>
    from fast_rcnn.config import cfg
  File "/hdd/panyu/Projects/Faster-rcnn_TF-master/tools/../lib/fast_rcnn/__init__.py", line 10, in <module>
    from . import test
  File "/hdd/panyu/Projects/Faster-rcnn_TF-master/tools/../lib/fast_rcnn/test.py", line 6, in <module>
    from utils.cython_nms import nms, nms_new
ImportError: /hdd/panyu/Projects/Faster-rcnn_TF-master/tools/../lib/utils/cython_nms.so: undefined symbol: PyFPE_jbuf

why does this happen?

**Comment by ghost** [comment]
Now I know the reason. I delete this file and rebuild it, then it works!

**Comment by ankita-kalra** [comment]
You delete what file?

**Comment by ankita-kalra** [comment]
What is the file you delete?
