### ISSUE TITLE
Training model error 

### ISSUE THREAD

**Issue by Pratosha-29** [smallcorgi/Faster-RCNN_TF#260]
Hi,
I am currently facing this error while I am trying to train VGGnet from 21 classes to 7.
nvidia@tegra-ubuntu:~/TensorFlowTX2/Faster-RCNN_TF_changes$ ./experiments/scripts/faster_rcnn_end2end.sh GPU 0 /home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy pascal_voc
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
+ DEV=GPU
+ DEV_ID=0
+ NET=/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy
+ DATASET=pascal_voc
+ array=($@)
+ len=4
+ EXTRA_ARGS=
+ EXTRA_ARGS_SLUG=
+ case $DATASET in
+ TRAIN_IMDB=/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VOCdevkit16/VOCdevkit/VOC2007/ImageSets/Main/voc_2007_trainval
+ TEST_IMDB=voc_2007_test
+ PT_DIR=pascal_voc
+ ITERS=70000
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/faster_rcnn_end2end_/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy_.txt.2018-01-30_16-57-32
+ exec
++ tee -a experiments/logs/faster_rcnn_end2end_/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy_.txt.2018-01-30_16-57-32
tee: experiments/logs/faster_rcnn_end2end_/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy_.txt.2018-01-30_16-57-32: No such file or directory
+ echo Logging output to experiments/logs/faster_rcnn_end2end_/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy_.txt.2018-01-30_16-57-32
Logging output to experiments/logs/faster_rcnn_end2end_/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VGG_imagenet.npy_.txt.2018-01-30_16-57-32
+ python ./tools/train_net.py --device GPU --device_id 0 --weights data/pretrain_model/VGG_imagenet.npy --imdb /home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VOCdevkit16/VOCdevkit/VOC2007/ImageSets/Main/voc_2007_trainval --iters 70000 --cfg experiments/cfgs/faster_rcnn_end2end.yml --network VGGnet_train
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
voc_2007_train
voc_2007_val
voc_2007_trainval
voc_2007_test
kitti_train
kitti_val
kitti_trainval
kitti_test
nthu_71
nthu_370
Called with args:
Namespace(cfg_file='experiments/cfgs/faster_rcnn_end2end.yml', device='GPU', device_id=0, imdb_name='/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VOCdevkit16/VOCdevkit/VOC2007/ImageSets/Main/voc_2007_trainval', max_iters=70000, network_name='VGGnet_train', pretrained_model='data/pretrain_model/VGG_imagenet.npy', randomize=False, set_cfgs=None, solver=None)
Using config:
{'DATA_DIR': '/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data',
 'DEDUP_BOXES': 0.0625,
 'EPS': 1e-14,
 'EXP_DIR': 'faster_rcnn_end2end',
 'GPU_ID': 0,
 'IS_MULTISCALE': False,
 'MATLAB': 'matlab',
 'MODELS_DIR': '/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/models/pascal_voc',
 'PIXEL_MEANS': array([[[ 102.9801,  115.9465,  122.7717]]]),
 'RNG_SEED': 3,
 'ROOT_DIR': '/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes',
 'TEST': {'BBOX_REG': True,
          'DEBUG_TIMELINE': False,
          'HAS_RPN': True,
          'MAX_SIZE': 1000,
          'NMS': 0.3,
          'PROPOSAL_METHOD': 'selective_search',
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000,
          'SCALES': [600],
          'SVM': False},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_SIZE': 128,
           'BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'BBOX_NORMALIZE_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZE_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_NORMALIZE_TARGETS': True,
           'BBOX_NORMALIZE_TARGETS_PRECOMPUTED': True,
           'BBOX_REG': True,
           'BBOX_THRESH': 0.5,
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'DEBUG_TIMELINE': False,
           'DISPLAY': 10,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'GAMMA': 0.1,
           'HAS_RPN': True,
           'IMS_PER_BATCH': 1,
           'LEARNING_RATE': 0.001,
           'MAX_SIZE': 1000,
           'MOMENTUM': 0.9,
           'PROPOSAL_METHOD': 'gt',
           'RPN_BATCHSIZE': 256,
           'RPN_BBOX_INSIDE_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000,
           'SCALES': [600],
           'SNAPSHOT_INFIX': '',
           'SNAPSHOT_ITERS': 5000,
           'SNAPSHOT_PREFIX': 'VGGnet_fast_rcnn',
           'STEPSIZE': 5000,
           'USE_FLIPPED': True,
           'USE_PREFETCH': False},
 'USE_GPU_NMS': True}
Traceback (most recent call last):
  File "./tools/train_net.py", line 81, in <module>
    imdb = get_imdb(args.imdb_name)
  File "/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/tools/../lib/datasets/factory.py", line 82, in get_imdb
    raise KeyError('Unknown dataset: {}'.format(name))
KeyError: 'Unknown dataset: /home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VOCdevkit16/VOCdevkit/VOC2007/ImageSets/Main/voc_2007_trainval'

Kindly help. Totally new to this
@smallcorgi

**Comment by woxihuanchirou** [comment]
try to use 
/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VOCdevkit2007/VOC2007/ImageSets/Main/voc_2007_trainval
instead of 
/home/nvidia/TensorFlowTX2/Faster-RCNN_TF_changes/data/VOCdevkit16/VOCdevkit/VOC2007/ImageSets/Main/voc_2007_trainval
