### ISSUE TITLE
out of memory in GTX1080

### ISSUE THREAD

**Issue by socosting** [smallcorgi/Faster-RCNN_TF#27]
I trained this model on a machine that has GTX1080 and 16 GB memory.It always ends up with:

out of memory
invalid argument
an illegal memory access was encountered
E tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:662] failed to record completion event; therefore, failed to create inter-stream dependency
I tensorflow/stream_executor/stream.cc:3788] stream 0x50b3390 did not memcpy host-to-device; source: 0x7f1c216f6e60
E tensorflow/stream_executor/stream.cc:272] Error recording event in stream: error recording CUDA event on stream 0x50989c0: CUDA_ERROR_ILLEGAL_ADDRESS; not marking stream as bad, as the Event object may be at fault. Monitor for further errors.
E tensorflow/stream_executor/cuda/cuda_event.cc:49] Error polling for event status: failed to query event: CUDA_ERROR_ILLEGAL_ADDRESS
F tensorflow/core/common_runtime/gpu/gpu_event_mgr.cc:198] Unexpected Event status: 1
[1]    6900 abort (core dumped)  python ./faster_rcnn/train_net.py --gpu 0 --weights  --imdb voc_2007_trainval

and README.md said:
Requirements: hardware
For training the end-to-end version of Faster R-CNN with VGG16, 3G of GPU memory is sufficient (using CUDNN)

what's the problem?

**Comment by shangwenxiang** [comment]
I use K80 and tensorflow tf 0.12，when I make in lib,it is error:

 cd lib/
root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# clear
root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# make
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
rm -rf build
bash make.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(36): error: identifier "__builtin_ia32_monitorx" is undefined

/usr/lib/gcc/x86_64-linux-gnu/5/include/mwaitxintrin.h(42): error: identifier "__builtin_ia32_mwaitx" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00007a14_00000000-7_roi_pooling_op_gpu.cu.cpp1.ii".
root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# cd ..
root@gpu4:/home/caicloud/Faster-RCNN_TF# ./RunDemo.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "./tools/demo.py", line 5, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/caicloud/Faster-RCNN_TF/tools/../lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
root@gpu4:/home/caicloud/Faster-RCNN_TF#



So I change lib/make.sh,set #CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED',
when compile,it is:


root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# make
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
rm -rf build
bash make.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# cd ..
root@gpu4:/home/caicloud/Faster-RCNN_TF# ./RunDemo.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "./tools/demo.py", line 5, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/caicloud/Faster-RCNN_TF/tools/../lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms
root@gpu4:/home/caicloud/Faster-RCNN_TF#



How should I do,CPU test is normal!

**Comment by ghost** [comment]
I trained this model on a machine that has GTX1060 and 6 GB memory.It always runs normal.

**Comment by riadhayachi** [comment]
minimum memory to use is 4GB

**Comment by fangyan93** [comment]
@minbinL Hello, have you solved this problem? I am also using a GTX1080 to train this model on my dataset, this error occurs in the middle of training, and I trained it successfully once, but it keeps showing up now, any idea?

**Comment by baizhenmao95** [comment]
Oh, I meet the same problem with you. Did you solve it? I'll verrrrrrrrrrry appreciate for your help!

**Comment by baizhenmao95** [comment]
Oh, I meet the same problem with you. Did you solve it? I'll verrrrrrrrrrry appreciate for your help!@minbinL
