### ISSUE TITLE
meet this issue  when I make the flie

### ISSUE THREAD

**Issue by fireflyviolet** [smallcorgi/Faster-RCNN_TF#293]
have anyone met this issue when make the file? 

setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 49, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1

thanks for your help.

**Comment by LiuPearl1** [comment]
You should check your Python version. In python 3.5 or 3.6, it uses items take place of iteritems.
