### ISSUE TITLE
run demo erro

### ISSUE THREAD

**Issue by starxhong** [smallcorgi/Faster-RCNN_TF#302]
,I need help, I put the VGGnet_fast_rcnn_iter_70000.ckpt under the ./tools but when I run the demo
the terminal display those code :
Faster-RCNN_TF-master$ python ./tools/demo.py --model VGGnet_fast_rcnn_iter_70000.ckpt
Traceback (most recent call last):
  File "./tools/demo.py", line 11, in <module>
    from networks.factory import get_network
  File "/home/huster/ydy/Faster-RCNN_TF-master/tools/../lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "/home/huster/ydy/Faster-RCNN_TF-master/tools/../lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "/home/huster/ydy/Faster-RCNN_TF-master/tools/../lib/networks/network.py", line 3, in <module>
    import roi_pooling_layer.roi_pooling_op as roi_pool_op
  File "/home/huster/ydy/Faster-RCNN_TF-master/tools/../lib/roi_pooling_layer/roi_pooling_op.py", line 5, in <module>
    _roi_pooling_module = tf.load_op_library(filename)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /home/huster/ydy/Faster-RCNN_TF-master/tools/../lib/roi_pooling_layer/roi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by SolinTao** [comment]
@VersionHX  I had the same problem. Have you solved it yet?

**Comment by zhufengli** [comment]
I had the same problem too

**Comment by SolinTao** [comment]
@zhufengli  you need to modify the file(lib/roi_pooling_layer/roi_pooling_op.cc) with [here](https://github.com/crazymxm/Faster-RCNN_TF/commit/0dcb55cebeaa85c9f0a46ff62384bbeaae98323e).

**Comment by helenalee16888** [comment]
I had the same problem, and I found a solution[https://github.com/smallcorgi/Faster-RCNN_TF/issues/50#issuecomment-268323944](url) but it didn't work for me.

**Comment by XiaoningLiu123** [comment]
modify lib/make.sh as follows:
``TF_INC=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_include())')
TF_LIB=$(python -c 'import tensorflow as tf; print(tf.sysconfig.get_lib())')

CUDA_PATH=/usr/local/cuda/
CXXFLAGS=''

if [[ "$OSTYPE" =~ ^darwin ]]; then
	CXXFLAGS+='-undefined dynamic_lookup'
fi

cd roi_pooling_layer

if [ -d "$CUDA_PATH" ]; then
	nvcc -std=c++11 -c -o roi_pooling_op.cu.o roi_pooling_op_gpu.cu.cc \
		-I $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC $CXXFLAGS \
		-arch=sm_37

#	g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
#		roi_pooling_op.cu.o -I $TF_INC  -D GOOGLE_CUDA=1 -fPIC $CXXFLAGS \
#		-lcudart -L $CUDA_PATH/lib64
    g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc -D_GLIBCXX_USE_CXX11_ABI=0 \
        roi_pooling_op.cu.o -I $TF_INC -L $TF_LIB -ltensorflow_framework -D GOOGLE_CUDA=1 \
        -fPIC $CXXFLAGS -lcudart -L $CUDA_PATH/lib64

else
	g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
		-I $TF_INC -fPIC $CXXFLAGS
fi

cd ..
