### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by 245003478** [smallcorgi/Faster-RCNN_TF#318]
/home/mengfei/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mengfei/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/mengfei/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mengfei/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/mengfei/Desktop/faster_rcnn/lib/roi_pooling_layer/roi_pooling.so
2018-09-27 14:53:27.554253: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/rpn_cls_score:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("rpn_cls_prob_reshape:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_bbox_pred/rpn_bbox_pred:0", shape=(?, ?, ?, 36), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rois:0", shape=(?, 5), dtype=float32)
[<tf.Tensor 'conv5_3/conv5_3:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'rois:0' shape=(?, 5) dtype=float32>]
Traceback (most recent call last):
  File "./demo.py", line 115, in <module>
    net = get_network(args.demo_net)
  File "/home/mengfei/Desktop/faster_rcnn/lib/networks/factory.py", line 27, in get_network
    return lib.networks.VGGnet_test()
  File "/home/mengfei/Desktop/faster_rcnn/lib/networks/VGGnet_test.py", line 16, in __init__
    self.setup()
  File "/home/mengfei/Desktop/faster_rcnn/lib/networks/VGGnet_test.py", line 57, in setup
    .fc(4096, name='fc6')
  File "/home/mengfei/Desktop/faster_rcnn/lib/networks/network.py", line 23, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/mengfei/Desktop/faster_rcnn/lib/networks/network.py", line 269, in fc
    weights = self.make_var('weights', [dim, num_out], init_weights, trainable)
  File "/home/mengfei/Desktop/faster_rcnn/lib/networks/network.py", line 90, in make_var
    return tf.get_variable(name, shape, initializer=initializer, trainable=trainable)
  File "/home/mengfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1317, in get_variable
    constraint=constraint)
  File "/home/mengfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 1079, in get_variable
    constraint=constraint)
  File "/home/mengfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 425, in get_variable
    constraint=constraint)
  File "/home/mengfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 394, in _true_getter
    use_resource=use_resource, constraint=constraint)
  File "/home/mengfei/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/variable_scope.py", line 754, in _get_single_variable
    "but instead was %s." % (name, shape))
ValueError: Shape of a new variable (fc6/weights) must be fully defined, but instead was (?, 4096).

**Comment by HappyPK** [comment]
The same problem, have you solved it?

**Comment by 245003478** [comment]
I have not solved it,but i try another one , it can work 
this is the adderss: https://github.com/endernewton/tf-faster-rcnn
