### ISSUE TITLE
`AttributeError: 'module' object has no attribute 'RegisterShape'`

### ISSUE THREAD

**Issue by Chandrak1907** [smallcorgi/Faster-RCNN_TF#41]
hi ,
I am trying to execute this program on AWS and I am getting below error:

`Traceback (most recent call last):`
`File "./tools/demo.py", line 11, in <module>`
`    from networks.factory import get_network`
 ` File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/networks/__init__.py", line 8, in <module>`
  `  from .VGGnet_train import VGGnet_train`
  `File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 2, in <module>`
   ` from networks.network import Network`
  `File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/networks/network.py", line 4, in <module>`
   ` import roi_pooling_layer.roi_pooling_op_grad`
  `File "/home/ubuntu/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling_op_grad.py", line 7, in <module>`
   ` @tf.RegisterShape("RoiPool")`
`AttributeError: 'module' object has no attribute 'RegisterShape'`

Can any one suggest a solution to this problem? 
Thank you,

**Comment by oulcan** [comment]
Hi Chandrak1907,

The problem is actually about the tensorflow. RegisterShape attribute has been removed from its python API. 

> Shape functions for core ops have moved to C++ via REGISTER_OP(...).SetShapeFn(...). Python shape inference RegisterShape calls use the C++ shape functions with common_shapes.call_cpp_shape_fn. A future release will remove RegisterShape from python.

Quote from release r.0.11 notes.
[https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md#release-0110](url)

In the version r0.12 they removed it from python api. To solve this, you can use older version of tensorflow (r.0.11 is working, I tried it.) or you can change the FasterRCNN code to work with newer RegisterShape API.

**Comment by XiZiler** [comment]
In tensorflow0.12, I just modified `@tf.RegisterShape("RoiPool")` to `@ops.RegisterShape("RoiPool")`, and it worked for me. Maybe you could try it.

**Comment by civilman628** [comment]
this fix works for tf 1.0 as well.

**Comment by rogerguess** [comment]
Can anyone point me to commits in other repositories or other examples of how to do this:

"@tf.RegisterShape("RoiPool") to @ops.RegisterShape("RoiPool")"
