### ISSUE TITLE
make issue

### ISSUE THREAD

**Issue by aquibjaved** [smallcorgi/Faster-RCNN_TF#43]
```
cd $FRCN_ROOT/lib
make
```
After this step I am getting an error:

```
g++: error: roi_pooling_op.cu.o: No such file or directory
g++: error: GOOGLE_CUDA=1: No such file or directory

```
What is this problem, how can I fix it?

**Comment by raulpuric** [comment]
Same problem, please help.

**Comment by ICapalija** [comment]
Here is your problem:
`make.sh: line 13: nvcc: command not found`

**Solution**
If you are using the latest version of this project, then run:
`export PATH=$PATH:<path_to_cuda_folder>/bin`

**Comment by aquibjaved** [comment]
Do I need to install CUDA for this, I found that It require Nvidia GPU, But I have Radeon Graphics AMD.

**Comment by ICapalija** [comment]
CUDA only runs on NVIDIA cards.
But you can build CPU version of this project.

**Comment by sukritshankar** [comment]
Setting the following should make it work (it worked at least for me)
(1) export PATH=$PATH:/usr/local/cuda-8.0/bin/   (or your corresponding cuda path) for your terminal
(2) In make.sh file inside lib directory, do CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED'

**Comment by cjliux** [comment]
I have the similar problem, but the message is as follow:
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
skipping 'nms/gpu_nms.cpp' Cython extension (up-to-date)
rm -rf build
bash make.sh
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/__init__.py", line 75, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 22, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"m\n\x0eResourceHandle\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tB4\n\x18org.tensorflow.frameworkB\x13ResourceHandleProtoP\x01\xf8\x01\x01\x62\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'syntax'
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified
g++: error: roi_pooling_op.cu.o: No such file or directory
g++: error: GOOGLE_CUDA=1: No such file or directory

**Comment by Wheele9** [comment]
Where did you put the `CXXFLAGS='-D_MWAITXINTRIN_H_INCLUDED'`  line exactly in the make.sh?

**Comment by sukritshankar** [comment]
At line 4, where you see CXXFLAGS='' !!

**Comment by riadhayachi** [comment]
make.sh: line 13: nvcc: command not found
g++: error: roi_pooling_op.cu.o: No such file or directory
i get this error any solution

**Comment by ShunChengWu** [comment]
I think the easiest way to solve 
`make.sh: line 13: nvcc: command not found`
is to set the path of your CUDA within the lib/make.sh file 
@riadhayachi this should also solve your problem. 
`g++: error: roi_pooling_op.cu.o: No such file or directory`

In addition, if encounter `nvcc fatal   : Unknown option 'undefined'`
delete the `$CXXFLAGS` in the line of nvcc within lib/make.sh

**Comment by Jojo-Rabbit** [comment]
Can someone help me out, why this error is showing?
```
3 errors detected in the compilation of "roi_pooling_op_gpu.cu.cc".
g++: error: roi_pooling_op.cu.o: No such file or directory
```
