### ISSUE TITLE
Issue while training on new dataset

### ISSUE THREAD

**Issue by jmiller656** [smallcorgi/Faster-RCNN_TF#59]
I was training on a new dataset which is based on the format of VOC2007, and got 5000 iterations into training when there was a crash. It looks like something happened while trying to take a snapshot of the weights of the neural net. Any ideas on how to fix this?

Here's the error:
Traceback (most recent call last):
  File "./tools/train_net.py", line 95, in <module>
    max_iters=args.max_iters)
  File "Faster-RCNN_TF-master/tools/../lib/fast_rcnn/train.py", line 209, in train_net
    sw.train_model(sess, max_iters)
  File "Faster-RCNN_TF-master/tools/../lib/fast_rcnn/train.py", line 166, in train_model
    self.snapshot(sess, iter)
  File "Faster-RCNN_TF-master/tools/../lib/fast_rcnn/train.py", line 60, in snapshot
    sess.run(weights.assign(orig_0 * np.tile(self.bbox_stds, (weights_shape[0],1))))
ValueError: operands could not be broadcast together with shapes (4096,84) (4096,32)

**Comment by jmiller656** [comment]
Fixed it, turns out there's a variable for the number of classes inside lib/networks/VGGNet_train.py named 'n_classes'. This was set to 21, despite the fact that my new dataset only has 8 classes
