### ISSUE TITLE
Failed to run demo

### ISSUE THREAD

**Issue by dakshvar22** [smallcorgi/Faster-RCNN_TF#63]
Hi I have downloaded the file - VGGnet_fast_rcnn_iter_70000.ckpt
I try running the demo using the command - 
python ./tools/demo.py --model VGGnet_fast_rcnn_iter_70000.ckpt

I get this error - 

> Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
> Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
> Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
> Tensor("rpn_cls_score/rpn_cls_score:0", shape=(?, ?, ?, 18), dtype=float32)
> Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
> Tensor("rpn_cls_prob_reshape:0", shape=(?, ?, ?, 18), dtype=float32)
> Tensor("rpn_bbox_pred/rpn_bbox_pred:0", shape=(?, ?, ?, 36), dtype=float32)
> Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
> Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
> Tensor("rois:0", shape=(?, 5), dtype=float32)
> [<tf.Tensor 'conv5_3/conv5_3:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'rois:0' shape=(?, 5) dtype=float32>]
> Tensor("fc7/fc7:0", shape=(?, 4096), dtype=float32)
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> W tensorflow/core/framework/op_kernel.cc:993] Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> Traceback (most recent call last):
>   File "./tools/demo.py", line 117, in <module>
>     saver.restore(sess, args.model)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1439, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 767, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1015, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1035, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> 	 [[Node: save/RestoreV2_25 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_25/tensor_names, save/RestoreV2_25/shape_and_slices)]]
> 	 [[Node: save/RestoreV2_26/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_155_save/RestoreV2_26", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
> 
> Caused by op u'save/RestoreV2_25', defined at:
>   File "./tools/demo.py", line 116, in <module>
>     saver = tf.train.Saver()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1051, in __init__
>     self.build()
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1081, in build
>     restore_sequentially=self._restore_sequentially)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 675, in build
>     restore_sequentially, reshape)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 402, in _AddRestoreOps
>     tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 242, in restore_op
>     [spec.tensor.dtype])[0])
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 668, in restore_v2
>     dtypes=dtypes, name=name)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2395, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1264, in __init__
>     self._traceback = _extract_stack()
> 
> NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for VGGnet_fast_rcnn_iter_70000.ckpt
> 	 [[Node: save/RestoreV2_25 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_25/tensor_names, save/RestoreV2_25/shape_and_slices)]]
> 	 [[Node: save/RestoreV2_26/_33 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_155_save/RestoreV2_26", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by chaituNova** [comment]
I believe you are not providing the correct path to the downloaded `VGGnet_fast_rcnn_iter_70000.ckpt` . Provide the path like below: 
`python ./tools/demo.py --model /path/toVGGnet_fast_rcnn_iter_70000.ckpt`
