### ISSUE TITLE
snapshot with a new dataset

### ISSUE THREAD

**Issue by rayanelleuch** [smallcorgi/Faster-RCNN_TF#66]
I created a new imdb to train on a new kind of data (not coco, not pascal).

It took me some time but the all process during training is going well. But when it comes to take a snapshot I have a problem of broadcasting.

`Traceback (most recent call last):
  File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/home/rayan/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 225, in train_net
    sw.train_model(sess, max_iters)
  File "/home/rayan/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 179, in train_model
    self.snapshot(sess, iter)
  File "/home/rayan/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 61, in snapshot
    sess.run(net.bbox_weights_assign, feed_dict={net.bbox_weights: orig_0 * np.tile(self.bbox_stds, (weights_shape[0], 1))})
ValueError: operands could not be broadcast together with shapes (4096,84) (4096,28)`

My dataset have 6 labels, adding the background we arrive to 7. 7*4 = 28 (4 for  x1, y1, x2, y2).
And I guess 84 is the result of the number of labels in the Pascal Dataset. But I have hard time to see what to do to fix this problem.

Can anyone give me some ideas?

Also If someone could explain me what's happening in the snapshot I would be glad to know. I don't understand why not just saving the all model directly.

**Comment by ArturoDeza** [comment]
@rayanelleuch , did you solve this? Bumped into the same issue, but in my case I only have 1 class (2 including background).

**Comment by rayanelleuch** [comment]
@ArturoDeza  No I gave up after some time. But just tried by changing the values in the files: `Faster-RCNN_TF/lib/networks/VGGnet_train.py` and `Faster-RCNN_TF/lib/networks/VGGnet_test.py` and taking snapshot works now!  

Big thanks!

**Comment by towardthesea** [comment]
I think this [diff](https://github.com/smallcorgi/Faster-RCNN_TF/compare/master...TheLaurens:master) can help! In short, the author change the number of classes from 21 (VOC) to 81 (COCO).
