### ISSUE TITLE
error in 'Run script to train and test model' process

### ISSUE THREAD

**Issue by mysope** [smallcorgi/Faster-RCNN_TF#72]
Hi.
A When I run the 6th process, I get the following error.

6. Run script to train and test model
$ ./experiments/scripts/faster_rcnn_end2end.sh gpu 0 VGG16 pascal_voc

Has anybody solved it?

-------------------------------------------------------------------------------------------------------
...
assign pretrain model weights to conv2_2
assign pretrain model biases to conv2_2
assign pretrain model weights to conv2_1
assign pretrain model biases to conv2_1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 85, in __call__
    ret = func(*args)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/rpn_msr/proposal_target_layer_tf.py", line 48, in proposal_target_layer
    rois_per_image, _num_classes)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/rpn_msr/proposal_target_layer_tf.py", line 153, in _sample_rois
    _get_bbox_regression_labels(bbox_target_data, num_classes)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/rpn_msr/proposal_target_layer_tf.py", line 89, in _get_bbox_regression_labels
    bbox_targets[ind, start:end] = bbox_target_data[ind, 1:]
TypeError: slice indices must be integers or None or have an __index__ method
W tensorflow/core/framework/op_kernel.cc:975] Internal: Failed to run py callback pyfunc_2: see error log.
Traceback (most recent call last):
  File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 222, in train_net
    sw.train_model(sess, max_iters)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 161, in train_model
    run_metadata=run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Failed to run py callback pyfunc_2: see error log.
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_105, _recv_Placeholder_2_0, roi-data/PyFunc/input_2)]]

Caused by op u'roi-data/PyFunc', defined at:
  File "./tools/train_net.py", line 91, in <module>
    network = get_network(args.network_name)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/networks/factory.py", line 30, in get_network
    return networks.VGGnet_train()
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 20, in __init__
    self.setup()
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 77, in setup
    .proposal_target_layer(n_classes,name = 'roi-data'))
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "/home/nwkim/tensorflow-sample/Faster-RCNN_TF/tools/../lib/networks/network.py", line 186, in proposal_target_layer
    rois,labels,bbox_targets,bbox_inside_weights,bbox_outside_weights = tf.py_func(proposal_target_layer_py,[input[0],input[1],classes],[tf.float32,tf.float32,tf.float32,tf.float32,tf.float32])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 192, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 40, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Failed to run py callback pyfunc_2: see error log.
	 [[Node: roi-data/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], token="pyfunc_2", _device="/job:localhost/replica:0/task:0/cpu:0"](rpn_rois/_105, _recv_Placeholder_2_0, roi-data/PyFunc/input_2)]]

**Comment by zacwellmer** [comment]
yes, see my [pull request](https://github.com/smallcorgi/Faster-RCNN_TF/pull/73)

**Comment by mysope** [comment]
@zacwellmer Thanks. It works well. :+1:

**Comment by civilman628** [comment]
i meet the same issue. and now that works.
