### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by vpolflie** [smallcorgi/Faster-RCNN_TF#76]
Getting a segmentation fault after executing the demo in cpu mode.
Any ideas what causes this?
Using CUDA 8 and cudnn 5.0

**Comment by zacwellmer** [comment]
Where is it seg faulting?

**Comment by vpolflie** [comment]
The issue seems to occur at

 _, _= im_detect(sess, net, im) 
tools/demo.py line 125

When debugging the im_detect function i encountered the segmentation fault at:

cls_score, cls_prob, bbox_pred, rois = sess.run([net.get_output('cls_score'), net.get_output('cls_prob'), net.get_output('bbox_pred'),net.get_output('rois')], feed_dict=feed_dict,options=run_options, run_metadata=run_metadata)
lib/fast_rcnn/test.py line 179

Didn't debug any deeper since it occurs in a tensorflow function

**Comment by vpolflie** [comment]
I also adjusted the make.sh file in the lib directory to this:

```
if [ -d "$CUDA_PATH" ]; then
        nvcc -std=c++11 -c -o roi_pooling_op.cu.o roi_pooling_op_gpu.cu.cc \
                -I $TF_INC -D GOOGLE_CUDA=1 -x cu -Xcompiler -fPIC $CXXFLAGS \
                -arch=sm_37

        g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
        roi_pooling_op.cu.o -I $TF_INC  -D GOOGLE_CUDA=1 -fPIC $CXXFLAGS  -D_GLIBCXX_USE_CXX11_ABI=0 \
        -lcudart -L $CUDA_PATH/lib64
else
        g++ -std=c++11 -shared -o roi_pooling.so roi_pooling_op.cc \
                -I $TF_INC -fPIC $CXXFLAGS
fi

```

To fix the undefined symbol error i was getting when executing the demo. Similar to issue #50

**Comment by vpolflie** [comment]
My entire backtrace using gdb:

```
[Switching to Thread 0x7fffd5047700 (LWP 5069)]
0x00007fffd5d2c33b in std::_Function_handler<void (long long, long long), RoiPoolOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*)::{lambda(long long, long long)#1}>::_M_invoke(std::_Any_data const&, long long&&, std::_Any_data const&) ()
   from /home/vincent/Documents/Kaggle/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so
(gdb) backtrace
#0  0x00007fffd5d2c33b in std::_Function_handler<void (long long, long long), RoiPoolOp<Eigen::ThreadPoolDevice, float>::Compute(tensorflow::OpKernelContext*)::{lambda(long long, long long)#1}>::_M_invoke(std::_Any_data const&, long long&&, std::_Any_data const&) ()
   from /home/vincent/Documents/Kaggle/Faster-RCNN_TF/tools/../lib/roi_pooling_layer/roi_pooling.so
#1  0x00007fffeba953c9 in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#2  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#3  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#4  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#5  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#6  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#7  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#8  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#9  0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#10 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#11 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std-----Typ---Type <retur---Type ---Type <return> to continue, or q <retu---Type <return> to continue, or q <return> to quit---
::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#12 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#13 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#14 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#15 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#16 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#17 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#18 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#19 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#20 0x00007fffeba9539f in std::_Function_handler<void (long, long), Eigen::ThreadPoolDevice::parallelFor(long, Eigen::TensorOpCost const&, std::function<long (long)>, std::function<void (long, long)>) const::{lambda(long, long)#1}>::_M_invoke(std::_Any_data const&, long, long) () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#21 0x00007fffed08aa78 in Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::WorkerLoop(int) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#22 0x00007fffed08a240 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
#23 0x00007fffeacc5260 in ?? () from /home/vincent/anaconda2/lib/python2.7/site-packages/tensorflow/python/../../../../libstdc++.so.6
#24 0x00007ffff77c76ba in start_thread (arg=0x7fffd5047700) at pthread_create.c:333
#25 0x00007ffff6ded82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```

**Comment by SerhanGul** [comment]
I also have a Segmentation Fault while running demo.py on Ubuntu 16.04, tensorflow-gpu 0.12.0rc0 with CUDA 8.0.

```
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Quadro K2200, pci bus id: 0000:03:00.0)
Tensor("Placeholder:0", shape=(?, ?, ?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_conv/3x3/rpn_conv/3x3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rpn_cls_score/rpn_cls_score:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_cls_prob:0", shape=(?, ?, ?, ?), dtype=float32)
Tensor("rpn_cls_prob_reshape:0", shape=(?, ?, ?, 18), dtype=float32)
Tensor("rpn_bbox_pred/rpn_bbox_pred:0", shape=(?, ?, ?, 36), dtype=float32)
Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)
Tensor("conv5_3/conv5_3:0", shape=(?, ?, ?, 512), dtype=float32)
Tensor("rois:0", shape=(?, 5), dtype=float32)
[<tf.Tensor 'conv5_3/conv5_3:0' shape=(?, ?, ?, 512) dtype=float32>, <tf.Tensor 'rois:0' shape=(?, 5) dtype=float32>]
Tensor("fc7/fc7:0", shape=(?, 4096), dtype=float32)


Loaded network /home/guel/git/Faster-RCNN_TF/VGGnet_fast_rcnn_iter_70000.ckpt
Segmentation fault (core dumped)
```

**Comment by pierrebaque** [comment]
Hello,

Exact same issue on my side.

Cheers
Pierre

**Comment by vpolflie** [comment]
My gpu only has 2gb of memory so that isnt a possiblity for me

**Comment by hermitman** [comment]
Hi, @pierrebaque what is your tensorflow version? My program will crash on TF1.0 (both CPU & GPU), but runs fine on TF0.12 (both CPU & GPU). This make me feel that something changed in the tensorflow might broke some code... Any idea?

**Comment by YosukeHiguchi** [comment]
I am in the same situation as @vpolflie's . Have you solved it?

**Comment by lk251** [comment]
@vpolflie  I implemented your suggested change and it now training works for me https://github.com/lev-kusanagi/Faster-RCNN_TF/commit/7605be2bb8d49eb65a567bba531ff2b87f49b252
@YosukeHiguchi

**Comment by yanmenglu** [comment]
@lev-kusanagi ,Hello,when I run the Fasrter-Rcnn-TF  demo.py ,also met the problem "Segmentation fault (core dumped)", and my tensorflow version is 1.1.0.  Can you help me?if I can't update the tensorflow version,the problem can be solved.Thank you very much.

**Comment by YefeiGao** [comment]
I also encountered 'Segmentation Fault(core dumped)' problem as @serhannn was, while i found i had made a stupid mistake: I run gpu mode with cpu version of tensorflow. After update tensorflow-gpu & run make one more time it worked well. With Ubuntu16.04 & CUDA8 & cudnn5 & tensorflow-gpu-1.3.0

**Comment by jasonxavier** [comment]
@vpolflie I have same error 'Segmentation Fault(core dumped)'  when I run CPU mode. Have you resolved it?
