### ISSUE TITLE
Missing shape in roi_pool (layer_input to fc6)

### ISSUE THREAD

**Issue by sean-wong** [smallcorgi/Faster-RCNN_TF#87]
The roi_pool (input to fc) seems to be missing its shape Tensor("pool_5:0", dtype=float32) and causing the training to break. Any ideas (I installed tensorflow 1.0). Thanks!

Traceback (most recent call last):
  File "./tools/train_net.py", line 91, in <module>
    network = get_network(args.network_name)
  File "Faster-RCNN_TF/tools/../lib/networks/factory.py", line 30, in get_network
    return networks.VGGnet_train()
  File "Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 20, in __init__
    self.setup()
  File "Faster-RCNN_TF/tools/../lib/networks/VGGnet_train.py", line 83, in setup
    .fc(4096, name='fc6')
  File "Faster-RCNN_TF/tools/../lib/networks/network.py", line 25, in layer_decorated
    layer_output = op(self, layer_input, *args, **kwargs)
  File "Faster-RCNN_TF/tools/../lib/networks/network.py", line 243, in fc
    feed_in, dim = (input, int(input_shape[-1]))
TypeError: __int__ returned non-int (type NoneType)

**Comment by osimeoni** [comment]
Did you find out what is causing the error ?

**Comment by forwardwfg** [comment]
i meet the same problem now. Did you solve it ?
