### ISSUE TITLE
Fail to Train 

### ISSUE THREAD

**Issue by shangwenxiang** [smallcorgi/Faster-RCNN_TF#95]
I run ./train_Model.sh,and train_Model.sh is:

./experiments/scripts/faster_rcnn_end2end.sh   cpu  0 VGG16 pascal_voc

finally,it is error:

Normalizing targets
done
Solving...
Traceback (most recent call last):
  File "./tools/train_net.py", line 96, in <module>
    max_iters=args.max_iters)
  File "/Users/shang/mlSoftware/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 264, in train_net
    sw.train_model(sess, max_iters)
  File "/Users/shang/mlSoftware/Faster-RCNN_TF/tools/../lib/fast_rcnn/train.py", line 114, in train_model
    rpn_cross_entropy = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(rpn_cls_score, rpn_label))
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1684, in sparse_softmax_cross_entropy_with_logits
    labels, logits)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/nn_ops.py", line 1533, in _ensure_xent_args
    "named arguments (labels=..., logits=..., ...)" % name)
ValueError: Only call `sparse_softmax_cross_entropy_with_logits` with named arguments (labels=..., logits=..., ...)

**Comment by ljdang** [comment]
@shangwenxiang You can change the flie "/lib/fast_rcnn/train.py", line 114 to rpn_cross_entropy = tf.reduce_mean(tf.nn.sparse_softmax_cross_entropy_with_logits(logits=rpn_cls_score, labels=rpn_label)), the same to line 129.
