### ISSUE TITLE
GPU compile error

### ISSUE THREAD

**Issue by shangwenxiang** [smallcorgi/Faster-RCNN_TF#96]
I compile withK8,it is error:

root@gpu4:/home/caicloud/Faster-RCNN_TF# cd lib/
root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# make
python setup.py build_ext --inplace
running build_ext
skipping 'utils/bbox.c' Cython extension (up-to-date)
skipping 'utils/nms.c' Cython extension (up-to-date)
skipping 'nms/cpu_nms.c' Cython extension (up-to-date)
rm -rf build
bash make.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
root@gpu4:/home/caicloud/Faster-RCNN_TF/lib# cd ..
root@gpu4:/home/caicloud/Faster-RCNN_TF# ./RunDemo.sh
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "./tools/demo.py", line 5, in <module>
    from fast_rcnn.nms_wrapper import nms
  File "/home/caicloud/Faster-RCNN_TF/tools/../lib/fast_rcnn/nms_wrapper.py", line 10, in <module>
    from nms.gpu_nms import gpu_nms
ImportError: No module named gpu_nms

**Comment by AlbertoBenini** [comment]
Hi, I have the same issue, have you find how to fix it?

Ok, I solved it following the solution here  https://github.com/smallcorgi/Faster-RCNN_TF/issues/90
